server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lewisdawson/spring-cloud-demo-config-repo
#          uri: ${HOME}/dev/noodle/spring-cloud-demo-config-repo
          cloneOnStart: true